### ISSUE TITLE
[ BACK ] Publicar Vagas

### ISSUE THREAD

**Issue by kauaneiras** [FGA0138-MDS-Ajax/2023-2-ANTARES#12]
# Criar uma rota na API para publicar vagas
## Tasks
- [x] Criar modelo de vagas contendo:
  - [ ] Email do Criador - obrigatório
  - [ ] Titulo - obrigatório
  - [ ] Descrição - obrigatório
  - [ ] Contato - obrigatório
  - [ ] Link - obrigatório
  - [ ] Data de Publicação - opcional
  - [ ] Data de Encerramento - opcional
- [x] Caso não seja dada uma data de publicação, será publicado na mesma hora
- [ ] Caso não seja dada uma data de encerramento, será encerrado 30 dias depois da publicação
- [ ] Obrigatório que o email do usuário exista no banco de dados
- [ ] Obrigatório que o usuário tenha as roles 3, 4 ou 5, que são as holes que permitem publicação
- [x] Criar collection Mongo
- [x] Retornar objeto/erro da requisição
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
- ### Para publicar vagas, será necessário acessar a rota: http://${URL}/api/vagas
- ### O objeto deve ser enviado pelo body em formato json:
   {
       "criadorEmail": "kauante@hotmail.com",
       "titulo": "Desenvolvedor Front-End",
       "descricao": "Procuramos um desenvolvedor front-end experiente para se juntar à nossa equipe.",
       "contato": "contato@empresa.com",
       "link": "https://www.empresa.com/carreiras"
   }
