### ISSUE TITLE
[ FRONT ] Publicar Vagas

### ISSUE THREAD

**Issue by kauaneiras** [FGA0138-MDS-Ajax/2023-2-ANTARES#14]
# Criar uma tela para cadastro de vagas
## Tasks
- [x] Criar Formulario de cadastro de vagas contendo:
  - [x] Titulo da Vaga - obrigatório
  - [x] Descrição - obrigatório
  - [x] Contato - obrigatório
  - [x] Link - obrigatório
  - [x] Data de Publicação programável  - opcional
  - [x] Data de Encerramento - opcional
- [x] Layout precisa ser responsivo
- [x] Fazer um botão ao lado de cada titulo de input que ao colocar mouse em cima, descreve o que deve ter ali
- [x] Fazer envio de dados para a API
- [x] Retornar respostando envio de dados para API
