### ISSUE TITLE
[ FRONT ] Feed 

### ISSUE THREAD

**Issue by LucasGSAntunes** [FGA0138-MDS-Ajax/2023-2-ANTARES#17]
# Criar uma tela do feed de vagas cadastradas
## Tasks
- [x] Criar lista de cards com resumo da vaga
- [x] Abrir modal ao clicar na vaga
- [x] Criar o layout da modal
- [x] Layout precisa ser responsivo
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by LucasGSAntunes** [comment]
Finalizada
