### ISSUE TITLE
[ FRONT ] Calendário

### ISSUE THREAD

**Issue by LucasGSAntunes** [FGA0138-MDS-Ajax/2023-2-ANTARES#31]
# Criar backend do feed de vagas cadastradas
## Tasks
- [x] Criar layout do calendário
- [x] Criar botões de próxima página, página anterior e página atual
- [ ] Criar modal de Adicionar vaga
- [ ] Integrar modal de adicionar vaga com método post create evento
- [ ] Mostrar eventos no calendário
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
