### ISSUE TITLE
[BACKEND] Setup inicial do projeto

### ISSUE THREAD

**Issue by matix0** [FGA0138-MDS-Ajax/2023-2-ANTARES#4]
# Criar o banco de dados
## Tasks
- [ ] Setup de modulos que serao utilizados (NodeJs, TypeScript, Express, TypeORM)
- [ ] Criar a tabela de usuarios
- [ ] Configurar chamada de api

## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
- [ ] Metodo POST de Registro
- [ ] Metodo GET de Login
