### ISSUE TITLE
[ BACK ] Registrar Usuário

### ISSUE THREAD

**Issue by samuelvictorol** [FGA0138-MDS-Ajax/2023-2-ANTARES#5]
# Criar Enpoint para registrar novos usuários no sistema 
## Tasks
- [x] Criar o endpoint para Registrar novos usuários
- [x] Adicionar funcionalidade correspondente ao endpoint
- [x ] Criar collection Mongo
- [x] Retornar objeto/erro da requisição
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
UsuarioSchema
  login: {
        type: String,
        required: true,
        unique: true
    },
    senha:{
        type: String,
        required: true
    },
    email:{
        type: String,
        required: true,
        unique: true
    },
    user_image:{
        type: String,
        required: false
    },
    role: {
        type: Number,
        required: true
    }

## Branch Relacionada:
- [feature/registrar-login](https://github.com/FGA0138-MDS-Ajax/2023-2-ANTARES/tree/feature-BACK/registrar-login)
## Evidências
